### ISSUE TITLE
Downloads older version of Fava

### ISSUE THREAD

**Issue by MickMorley** [alexiri/docker-fava#1]
When using your docker image, the Fava version installed is 1.7.  I see that your dockerfile uses the master branch which should be the most recent version.

I also added an ENV variable to say v1.10 but it still installed 1.7.

`/app # fava --version`
`fava, version 1.7`

**Comment by alexiri** [comment]
Yes, that's because it will only get updated when the docker image is rebuilt.

**Comment by MickMorley** [comment]
My image is new from today and v1.7 is still the newest Fava version that is pulled.  Do you think its because of the environment? It only installs v1.7 because of an older version of Python?

**Comment by alexiri** [comment]
If what you did was "docker pull alexiri/fava:0.6.4", what you downloaded was the last image built by dockerhub [6 months ago](https://cloud.docker.com/repository/docker/alexiri/fava/tags). The latest tag is even older, but I wasn't really using it so I never bothered keeping it up to date. I've just triggered a new build for you, though, it should be done in a about an hour.
